### ISSUE TITLE
Use rxn_offsets instead of rxn_pointers

### ISSUE THREAD

**Issue by cguzman95** [compdyn/partmc#111]
I'm working on GPU implementation, and I need to copy the contents of RXN structure to another structure to improve the memory access on GPU. The case is that using the rxn_pointers, **I don't know how much has to copy for the last value**.

Thus, I propose to save an array of rxn_offsets. The first value will be always zero (since to access the first value we don't need to move the pointer), the second will be the length of the first rxn, and go on. This is very similar to the implementation of SPARSE matrix

What do you think @mattldawson ?

**Comment by mattldawson** [comment]
sounds like a good idea to me. we should probably do the same for the `aero_rep` and `sub_model` pointers too, just to be consistent.

**Comment by cguzman95** [comment]
Ok I will do the three cases

**Comment by cguzman95** [comment]
Another related question, can I move n_rxn away from condensed structure? (to model_data->n_rxn) It difficulties dealing with RXN and I think away from it will be more clear and easy to identify

**Comment by mattldawson** [comment]
That's fine with me. Can you do the same for `n_aero_rep`, `n_aero_phase`, and `n_sub_model` too? Just so everything works the same.

**Comment by cguzman95** [comment]
Yep

**Comment by cguzman95** [comment]
Done on issue 99
