### ISSUE TITLE
optical properties for pure-BC fails

### ISSUE THREAD

**Issue by mwest1066** [compdyn/partmc#18]
If a particle is pure BC then the Mie code in MOSAIC dies with the error message:

```
THE UPPER LIMIT FOR ACAP IS NOT ENOUGH. SUGGEST GET DETAILED OUTPUT AND MODIFY SUBROUTINE
```

For now we work around this by not creating pure-BC particles.

**Comment by jcurtis2** [comment]
This is a MOSAIC issue. Pull request to handle pure-BC particles this will be submitted there.
