### ISSUE TITLE
Avoid hard-coded values on reaction defines

### ISSUE THREAD

**Issue by cguzman95** [compdyn/partmc#97]
There are hardcoded values in each rxn_ file like:

#define NUM_INT_PROP_ 2
#define NUM_FLOAT_PROP_ 7

and some -1 and others. Improve indices like NUM_REACT_ and NUM_PROD to sum this data and have fewer indices if it's possible, otherwise, put NUM_INT_PROP_ and the others inside RXN, on the integer reaction part

**Comment by mattldawson** [comment]
hi @cguzman95 - these will go away entirely after the somewhat mythical version 2.0. Can we put this off until then? these indices are already very difficult to maintain and I'm not convinced this would provide much of a performance increase. close if you agree

**Comment by cguzman95** [comment]
Yep, this is for version 2.0. We will see how this is working on 2.0, so at the moment it's unimportant
