### ISSUE TITLE
GPU: Fix RXN sorting

### ISSUE THREAD

**Issue by cguzman95** [compdyn/partmc#98]
I was testing a GPU optimization of sorting the rxn data at the start, starting RXN by reactions with "few zeros" to reactions with "a lot of zeros".

The sort was correct, but the program crashes. I RECENTLY NOTICED that rate_constants needs to be sorted following the RXN order to follow consistence. It's pending fixing this rate_constants and testing if this fixes the issue.

**Comment by cguzman95** [comment]
Update: Seems no improving doing this for GPU (same time execution)

**Comment by mattldawson** [comment]
should we close this then? we've removed the rate constants array as well

**Comment by cguzman95** [comment]
Well we removed rate constants and added rxn_env. I still thinks could be nice for the base version (cpu), but in any case it would be re-taked in the distant future, and this issue is for the GPU case. So I will close this
